name: Docker Image CI

on:
  schedule:
    - cron: '10 0 1 * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login -u scotch190 -p ${{ secrets.DOCKER_PSWD }}
        docker build -t scotch190/pyenv:latest .
        docker push scotch190/pyenv:latest
