name: Docker Image CI

on:
  schedule:
    - cron: '10 0 1 * *'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      USR_NAME: CocaButon60s
      IMG_NAME: $USR_NAME/pyenv:latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        echo ${{secrets.PAT_CLASSIC}} | docker login ghcr.io -u $USR_NAME --password-stdin
        docker build -t $IMG_NAME .