name: Docker Image CI

on:
  schedule:
    - cron: '10 0 1 * *'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      USER_NAME: CocaButon60s
      IMG_NAME: ghcr.io/$USER_NAME/pyenv:latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        echo ${{secrets.PAT_CLASSIC}} | docker login ghcr.io -u $USER_NAME --password-stdin
        docker build -t $IMG_NAME .
        docker push $IMG_NAME
